### ISSUE TITLE
Who likes T-Shirts?

### ISSUE THREAD

**Issue by bucaran** [tokyojs/tokyojs#7]
![t-shirt](https://cloud.githubusercontent.com/assets/8317250/7223354/ce79df1e-e75a-11e4-8856-08fc98eb89ff.png)

**Comment by yohei1126** [comment]
Looks good!

**Comment by tripu** [comment]
I can haz? :)

**Comment by bucaran** [comment]
@tripu The reception has been positive, so I will definitely bring up this topic during the next meetup in May.
