### ISSUE TITLE
[urgent] Map links on meetup page

### ISSUE THREAD

**Issue by andyhall** [tokyojs/tokyojs#8]
Map links for tonight's venue are broken!

On the [meetup page](https://www.meetup.com/tokyojs/events/232887456/), currently both links point to a google maps search for

    Toranomon 4-1-20 Tanakayama-bldg, Tokyo, jp

Something about the format confuses google, so it returns a map to Shinjuku. If you change the search string to

    Toranomon 4-1-20

it gives the correct map.

**Comment by andyhall** [comment]
@bucaran tag!

**Comment by bucaran** [comment]
@andyhall Thanks! Fixed.

**Comment by andyhall** [comment]
Link in the description works but the link in the metadata is still broken.

(I mean, if you go [here](https://www.meetup.com/tokyojs/events/232887456/) and click "Abeja INC", it points [here](https://www.google.com/maps?f=q&hl=en&q=https://www.google.com/maps/place/4%2BChome-1-20%2BToranomon,%2BMinato-ku,%2BT%25C5%258Dky%25C5%258D-to%2B105-0001,%2BJapan/@35.6653074,139.7415638,,+Tokyo,+jp))
